version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ryangst
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ryangst
    environment:
      - MONGO_INITDB_DATABASE=rinha-ryangst
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    env_file: .env
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb 
    networks:
      - ryangst
    command: bun --watch apps/api/src/index.ts
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - /app/node_modules

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
      target: development
    env_file: .env
    container_name: worker
    depends_on:
      - redis
      - mongodb
    networks:
      - ryangst
    command: bun --watch apps/worker/src/index.ts
    volumes:
      - ./apps/worker/src:/app/apps/worker/src
      - /app/node_modules
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}

  bullboard:
    container_name: bullboard-rinha
    image: venatum/bull-board:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001
    depends_on:
      - redis
    networks:
      - ryangst

networks:
  ryangst:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
