version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.api.address=:9999"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ryangst
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ryangst
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ryangst
    environment:
      - MONGO_INITDB_DATABASE=rinha-ryangst
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    env_file: .env
    container_name: api-rinha
    depends_on:
      - redis
      - mongodb
    networks:
      - ryangst
    command: bun --watch apps/api/src/index.ts
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.entrypoints=api"
      - "traefik.http.services.api.loadbalancer.server.port=9999"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
      target: development
    env_file: .env
    container_name: worker-rinha
    depends_on:
      - redis
      - mongodb
    networks:
      - ryangst
      - payment-processor
    command: bun --watch apps/worker/src/index.ts
    volumes:
      - ./apps/worker/src:/app/apps/worker/src
      - /app/node_modules
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/rinha-ryangst}
      - PAYMENT_PROCESSOR_URL_DEFAULT=${PAYMENT_PROCESSOR_URL_DEFAULT:-http://payment-processor-default:8080}
      - PAYMENT_PROCESSOR_URL_FALLBACK=${PAYMENT_PROCESSOR_URL_FALLBACK:-http://payment-processor-fallback:8080}
      - CONCURRENCY=${CONCURRENCY:-10}

  bullboard:
    container_name: bullboard-rinha
    image: venatum/bull-board:latest
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001
    depends_on:
      - redis
    networks:
      - ryangst 

networks:
  ryangst:
    driver: bridge
  payment-processor:
    external: true

volumes:
  mongodb_data:
  redis_data:
