name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup env files
        run: cp .env.example .env

      - name: Start all services
        run: docker compose up -d

      - run: docker compose exec -T api bun test
      - run: docker compose exec -T worker bun test
      - name: Cleanup
        if: always()
        run: docker compose down -v
        